### ISSUE TITLE
問題一覧ページの日付表示をなんとかしたい

### ISSUE THREAD

**Issue by asid21** [hibiki31/tmcit-db-front#4]
http://localhost:8080/problem
日付は、「年/月/日」までだけでいいと思う

問題一覧のページのカラムの順序を
日付 -> 問題 -> 問題番号
から
問題 -> 日付 -> 問題番号
の方がいいかも

**Comment by hibiki31** [comment]
https://github.com/hibiki31/virty/blob/master/web/src/views/TaskList.vue
150行目を参考にするといいかも

**Comment by asid21** [comment]
なんとかなった
